# Generated by Django 6.0.3 on 2026-04-05 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('dni', models.CharField(help_text='Debe tener exactamente 8 caracteres.', max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LoginFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10)),
                ('pagado', models.BooleanField(default=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='tienda.cliente')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='tienda.metodopago')),
            ],
            options={
                'ordering': ['-fecha_alquiler', '-id'],
                'permissions': [('can_simulate_sales', 'Puede simular ventas'), ('can_close_cash', 'Puede cerrar caja diaria')],
            },
        ),
        migrations.CreateModel(
            name='EventoDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='tienda.alquiler')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Año')),
                ('director', models.CharField(blank=True, max_length=120)),
                ('pais_origen', models.CharField(blank=True, max_length=80)),
                ('duracion_minutos', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='tienda.categoria')),
            ],
            options={
                'ordering': ['titulo', 'anio'],
                'unique_together': {('titulo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='tienda.pelicula')),
            ],
            options={
                'ordering': ['-cambiado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='alquiler',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='tienda.pelicula'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='alquiler',
            constraint=models.UniqueConstraint(fields=('cliente', 'pelicula', 'fecha_alquiler'), name='uniq_alquiler_cliente_pelicula_fecha'),
        ),
    ]
